### ISSUE TITLE
benchmark against https://github.com/BlueRaja/High-Speed-Priority-Queue-for-C-Sharp?

### ISSUE THREAD

**Issue by micampbell** [eiriktsarpalis/pq-tests#1]
The nuget by BlueRaja's OptimizedPriorityQueue (and at the github link above) is quite popular. Have you benchmarked your implementations against this? If not, then I may try it. If so, can you tell us the result? I am using this currently but would like a faster solution if it exists.

**Comment by eiriktsarpalis** [comment]
I have not. FWIW this is just a prototype and not intended for production use. The implementation under consideration for .NET can be found here: https://github.com/dotnet/runtime/pull/46009/. It would be great if you could provide any benchmarking numbers comparing the two implementations.
